trainer:
  _target_: pytorch_lightning.trainer.Trainer
  _partial_: True
  accelerator: gpu
  max_epochs: 40
  precision: bf16-mixed
  deterministic: True
  sync_batchnorm: True
  callbacks:
    - _target_: pytorch_lightning.callbacks.RichProgressBar
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      dirpath: ${checkpoint_dir}
      save_top_k: 1
      monitor: epoch
      mode: max
      filename: '{experiment_name}-{epoch:02d}-{step:03d}-{f1:.6f}${last_ckpt_suffix}'
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      dirpath: ${hydra:run.dir}/checkpoints
      save_top_k: 2
      monitor: f1
      mode: max
      filename: '{experiment_name}-{epoch:02d}-{step:03d}-{f1:.6f}${best_ckpt_suffix}'
      save_last: False
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      dirpath: ${hydra:run.dir}/checkpoints
      save_top_k: 2
      monitor: val_loss
      mode: min
      filename: '{experiment_name}-{epoch:02d}-{step:03d}-{val_loss:.6f}${best_val_loss_ckpt_suffix}'
      save_last: False
