trainer:
  _target_: pytorch_lightning.trainer.Trainer
  _partial_: True
  accelerator: "gpu"
  max_epochs: 3
  precision: bf16-mixed
  deterministic: True
  sync_batchnorm: True
  callbacks:
    - _target_: pytorch_lightning.callbacks.RichProgressBar
