datamodule:
  _target_: inz.data.data_module.XBDDataModule.create
  path: '${preprocessed_data_path}'
  drop_unclassified_channel: True
  events:
    inz.data.event.Tier3:
      - inz.data.event.Event.joplin_tornado
  val_fraction: 0.15
  test_fraction: 0.15
  train_batch_size: 24
  val_batch_size: 24
  test_batch_size: 24
