datamodule:
  _target_: inz.data.data_module.XBDDataModule.create
  path: '${preprocessed_data_path}'
  drop_unclassified_channel: True
  events:
    Tier3:
      - joplin_tornado
  val_fraction: 0.15
  test_fraction: 0.15
  train_batch_size: 64
  val_batch_size: 64
  test_batch_size: 64

experiment_name: test_experiment
