datamodule:
  _target_: inz.data.data_module_frnet.FRNetModule
  path: '${rescuenet_preprocessed_data_path_512}'
  train_batch_size: 36
  val_batch_size: 36
  test_batch_size: 36
  transform:
   _target_: torchvision.transforms.Compose
   transforms:
    - _target_: torchvision.transforms.RandomHorizontalFlip
      p: 0.5
    - _target_: torchvision.transforms.RandomApply
      p: 0.6
      transforms:
        - _target_: torchvision.transforms.RandomAffine
          degrees:
            - -10
            - 10
          scale:
            - 0.9
            - 1.1
          translate:
            - 0.1
            - 0.1
  num_workers: 2
