datamodule:
  _target_: inz.data.data_module.XBDDataModule.create
  path: '${preprocessed_data_path_512}'
  drop_unclassified_channel: True
  events:
    Tier1:
      - guatemala_volcano
      - hurricane_florence
      - hurricane_harvey
      - hurricane_matthew
      - hurricane_michael
      - mexico_earthquake
      - midwest_flooding
      - palu_tsunami
      - santa_rosa_wildfire
      - socal_fire
    Tier3:
      - joplin_tornado
      - lower_puna_volcano
      - moore_tornado
      - nepal_flooding
      - pinery_bushfire
      - portugal_wildfire
      - sunda_tsunami
      - tuscaloosa_tornado
      - woolsey_fire
  val_fraction: 0.1
  test_fraction: 0.0
  train_batch_size: 32
  val_batch_size: 32
  test_batch_size: 32
  transform:
   _target_: torchvision.transforms.Compose
   transforms:
    - _target_: torchvision.transforms.RandomHorizontalFlip
      p: 0.5
    - _target_: torchvision.transforms.RandomApply
      p: 0.6
      transforms:
        - _target_: torchvision.transforms.RandomAffine
          degrees: 
            - -10
            - 10 
          scale: 
            - 0.9
            - 1.1
          translate: 
            - 0.1
            - 0.1

