defaults:
  - trainer: default
  - datamodule: default
  - module: default
  - _self_

seed: 57
float32_matmul_precision: high
checkpoint_dir: ${hydra:run.dir}/checkpoints
project_name: inz

raw_data_path: data/xBD
preprocessed_data_path: data/xBD_processed
preprocessed_data_path_fullres: data/xBD_processed_noresize
preprocessed_data_path_512: data/xBD_processed_512

experiment_name: ???

hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    name: ${experiment_name}

wandb_dir: ${hydra:run.dir}
last_job_symlink_dir: outputs/${hydra:job.name}/latest_run


last_ckpt_suffix: '-last'
best_ckpt_suffix: '-best-f1'
best_val_loss_ckpt_suffix: '-best-val-loss'
best_challenge_score_ckpt_suffix: '-best-challenge-score'

resume_from_checkpoint: if_exists
